/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(clComplexToMag.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3ea22e92641a23fa69b49790a9241be8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <clenabled/clComplexToMag.h>
// pydoc.h is automatically generated in the build directory
#include <clComplexToMag_pydoc.h>

void bind_clComplexToMag(py::module& m)
{

    using clComplexToMag    = ::gr::clenabled::clComplexToMag;


    py::class_<clComplexToMag, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<clComplexToMag>>(m, "clComplexToMag", D(clComplexToMag))

        .def(py::init(&clComplexToMag::make),
           py::arg("openCLPlatformType"),
           py::arg("devSelector"),
           py::arg("platformId"),
           py::arg("devId"),
           py::arg("setDebug") = 0,
           D(clComplexToMag,make)
        )
        



        ;




}








