/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(clFFT.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d7f843a825cd801e0d5c17672511f04d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <clenabled/clFFT.h>
// pydoc.h is automatically generated in the build directory
#include <clFFT_pydoc.h>

void bind_clFFT(py::module& m)
{

    using clFFT    = ::gr::clenabled::clFFT;


    py::class_<clFFT, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<clFFT>>(m, "clFFT", D(clFFT))

        .def(py::init(&clFFT::make),
           py::arg("fftSize"),
           py::arg("clFFTDir"),
           py::arg("window"),
           py::arg("idataType"),
           py::arg("devSelector"),
           py::arg("platformId"),
           py::arg("devId"),
           py::arg("openCLPlatformType") = 4,
           py::arg("setDebug") = 0,
           py::arg("num_streams") = 1,
           py::arg("shift") = false,
           D(clFFT,make)
        )
        



        ;




}








