/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(clKernel1To1.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(cf69be0ef1a73953617a51fa5424b2e2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <clenabled/clKernel1To1.h>
// pydoc.h is automatically generated in the build directory
#include <clKernel1To1_pydoc.h>

void bind_clKernel1To1(py::module& m)
{

    using clKernel1To1    = ::gr::clenabled::clKernel1To1;


    py::class_<clKernel1To1, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<clKernel1To1>>(m, "clKernel1To1", D(clKernel1To1))

        .def(py::init(&clKernel1To1::make),
           py::arg("idataType"),
           py::arg("openCLPlatformType"),
           py::arg("devSelector"),
           py::arg("platformId"),
           py::arg("devId"),
           py::arg("kernelFnName"),
           py::arg("filename"),
           py::arg("setDebug") = 0,
           D(clKernel1To1,make)
        )
        



        ;




}








