/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(clMathOp.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f7e62506102f3c2e3fc80fc712b99832)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <clenabled/clMathOp.h>
// pydoc.h is automatically generated in the build directory
#include <clMathOp_pydoc.h>

void bind_clMathOp(py::module& m)
{

    using clMathOp    = ::gr::clenabled::clMathOp;


    py::class_<clMathOp, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<clMathOp>>(m, "clMathOp", D(clMathOp))

        .def(py::init(&clMathOp::make),
           py::arg("idataType"),
           py::arg("openCLPlatformType"),
           py::arg("operatorType"),
           py::arg("setDebug") = 0,
           D(clMathOp,make)
        )
        





        ;




}








