/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(clMagPhaseToComplex.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f179cc0acc9c36fe3e1dcedc929a1519)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <clenabled/clMagPhaseToComplex.h>
// pydoc.h is automatically generated in the build directory
#include <clMagPhaseToComplex_pydoc.h>

void bind_clMagPhaseToComplex(py::module& m)
{

    using clMagPhaseToComplex    = ::gr::clenabled::clMagPhaseToComplex;


    py::class_<clMagPhaseToComplex, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<clMagPhaseToComplex>>(m, "clMagPhaseToComplex", D(clMagPhaseToComplex))

        .def(py::init(&clMagPhaseToComplex::make),
           py::arg("openCLPlatformType"),
           py::arg("devSelector"),
           py::arg("platformId"),
           py::arg("devId"),
           py::arg("setDebug") = 0,
           D(clMagPhaseToComplex,make)
        )
        



        ;




}








