/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(clSignalSource.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c216c3d92fefcd74d3610d54efe6ddae)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <clenabled/clSignalSource.h>
// pydoc.h is automatically generated in the build directory
#include <clSignalSource_pydoc.h>

void bind_clSignalSource(py::module& m)
{

    using clSignalSource    = ::gr::clenabled::clSignalSource;


    py::class_<clSignalSource, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<clSignalSource>>(m, "clSignalSource", D(clSignalSource))

        .def(py::init(&clSignalSource::make),
           py::arg("idataType"),
           py::arg("openCLPlatformType"),
           py::arg("devSelector"),
           py::arg("platformId"),
           py::arg("devId"),
           py::arg("samp_rate"),
           py::arg("waveform"),
           py::arg("freq"),
           py::arg("amplitude"),
           py::arg("setDebug") = 0,
           D(clSignalSource,make)
        )
        



        ;




}








