/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(clSNR.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(299aa506f600b1baa33f293956c8ce76)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <clenabled/clSNR.h>
// pydoc.h is automatically generated in the build directory
#include <clSNR_pydoc.h>

void bind_clSNR(py::module& m)
{

    using clSNR    = ::gr::clenabled::clSNR;


    py::class_<clSNR, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<clSNR>>(m, "clSNR", D(clSNR))

        .def(py::init(&clSNR::make),
           py::arg("openCLPlatformType"),
           py::arg("devSelector"),
           py::arg("platformId"),
           py::arg("devId"),
           py::arg("nValue"),
           py::arg("kValue"),
           py::arg("setDebug") = 0,
           D(clSNR,make)
        )
        



        ;




}








