/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(clxcorrelate_fft_vcf.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4ffac8133784e29afaddeef2d77d4f29)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <clenabled/clxcorrelate_fft_vcf.h>
// pydoc.h is automatically generated in the build directory
#include <clxcorrelate_fft_vcf_pydoc.h>

void bind_clxcorrelate_fft_vcf(py::module& m)
{

    using clxcorrelate_fft_vcf    = ::gr::clenabled::clxcorrelate_fft_vcf;


    py::class_<clxcorrelate_fft_vcf, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<clxcorrelate_fft_vcf>>(m, "clxcorrelate_fft_vcf", D(clxcorrelate_fft_vcf))

        .def(py::init(&clxcorrelate_fft_vcf::make),
           py::arg("fftSize"),
           py::arg("num_inputs"),
           py::arg("openCLPlatformType"),
           py::arg("devSelector"),
           py::arg("platformId"),
           py::arg("devId"),
           py::arg("input_type") = 1,
           D(clxcorrelate_fft_vcf,make)
        )
        



        ;




}








