/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(clXCorrelate.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5c9cd9b432468d861fdd2f73277a763d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <clenabled/clXCorrelate.h>
// pydoc.h is automatically generated in the build directory
#include <clXCorrelate_pydoc.h>

void bind_clXCorrelate(py::module& m)
{

    using clXCorrelate    = ::gr::clenabled::clXCorrelate;


    py::class_<clXCorrelate, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<clXCorrelate>>(m, "clXCorrelate", D(clXCorrelate))

        .def(py::init(&clXCorrelate::make),
           py::arg("openCLPlatformType"),
           py::arg("devSelector"),
           py::arg("platformId"),
           py::arg("devId"),
           py::arg("setDebug"),
           py::arg("num_inputs"),
           py::arg("signal_length"),
           py::arg("data_type"),
           py::arg("data_size"),
           py::arg("max_search_index"),
           py::arg("decim_frames"),
           py::arg("async") = false,
           D(clXCorrelate,make)
        )
        



        ;




}








