/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(clXEngine.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(38f80702cc43718a0d1823b06b15b271)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <clenabled/clXEngine.h>
// pydoc.h is automatically generated in the build directory
#include <clXEngine_pydoc.h>

void bind_clXEngine(py::module& m)
{

    using clXEngine    = ::gr::clenabled::clXEngine;


    py::class_<clXEngine, gr::block, gr::basic_block,
        std::shared_ptr<clXEngine>>(m, "clXEngine", D(clXEngine))

        .def(py::init(&clXEngine::make),
           py::arg("openCLPlatformType"),
           py::arg("devSelector"),
           py::arg("platformId"),
           py::arg("devId"),
           py::arg("setDebug"),
           py::arg("data_type"),
           py::arg("polarization"),
           py::arg("num_inputs"),
           py::arg("output_format"),
           py::arg("first_channel"),
           py::arg("num_channels"),
           py::arg("integration"),
           py::arg("antenna_list"),
           py::arg("output_file") = false,
           py::arg("file_base") = "",
           py::arg("rollover_size_mb") = 0,
           py::arg("internal_synchronizer") = false,
           py::arg("sync_timestamp") = 0,
           py::arg("object_name") = "",
           py::arg("starting_chan_center_freq") = 0.,
           py::arg("channel_width") = 0.,
           py::arg("disable_output") = false,
           py::arg("cpu_integration") = 0,
           D(clXEngine,make)
        )
        



        ;




}








